spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/UserData?sslMode=REQUIRED
spring.datasource.username=HcuGyifqf2N47te.root
spring.datasource.password=muXoLN1nm5tS3MhK

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect